<?php

namespace ShoppingCartBundle\Repository;

/**
 * BanIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanIpRepository extends \Doctrine\ORM\EntityRepository
{


}
