<?php

namespace ShoppingCartBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByQuantity()
    {
//        $em = $this->getEntityManager();
//        $query = $em->createQuery(
//            'SELECT p
//    FROM ShoppingCartBundle:Product p
//    WHERE p.quantity > :quantity
//    ORDER BY p.quantity ASC'
//        )->setParameter('quantity');
//
//        return $query->getResult();

        return $this->createQueryBuilder("product")
            ->where("product.quantity > 0")
            ->orderBy("product.price", "ASC")
            ->getQuery()
            ->getResult();

    }
    public function test()
    {
        $db = $this->getEntityManager()->getConnection();

        $stm = $db->query('SELECT id, name, category');
        $stm->execute();
        // vrashta vsichki
        //return $stm->fetchAll(\PDO::FETCH_CLASS);

        // vrashtared po red
//        while($row = $stm->fetch()){
//            var_dump($row);
       // }


    }
}
