<?php

namespace ShoppingCartBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQuantity()
    {
        return $this->createQueryBuilder('product')
            ->where('product.quantity > 0')
            ->orderBy('product.price', 'ASC')
            ->getQuery()
            ->getResult();
    }
}